name = "deepend"
description = "Bounded & Unbounded memory storage pools with subpool capabilities"
version = "3.12"

authors = ["Brad Moore"]
maintainers = ["Brad Moore <bmoore.ada@gmail.com>"]
maintainers-logins = ["beemirang"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
website = "https://github.com/beemirang/deepend"
tags = ["ada", "memory", "storage-pools", "subpools"]
project-files = ["deepend.gpr"]

executables = ["test_bounded_dynamic_pools_ada2012",
               "binary_trees_with_bounded_subpools_ada2012"]
